### ISSUE TITLE
Source dbcripto

### ISSUE THREAD

**Issue by Katekko** [thebitnomad/Daybreak-Online-AIO#2]
In this step, would be nice to have the source of this exe for security reasons

- Utilize o [dbcrypto](https://drive.google.com/file/d/1ws-09pjo5N7151SdwjtFdQmqnTkEqZz-/view?usp=drive_link) para criptografar a Connection String. 

Can you provide the source?

**Comment by thebitnomad** [comment]
Thank you for your concern about security. While we understand your request for the source of the executable, currently, I don't have the source code available, since it has been made by Linekong. However, i want to assure you that the provided link to download dbcrypto is clean and free from viruses.

Additionally, you can consider utilizing a virtual machine as an extra layer of security when testing any executables. This approach can help isolate the executable from your main system and provide an added level of protection.

I appreciate your diligence in ensuring the safety of your environment. If you encounter any issues or have further questions, please don't hesitate to reach out.
